# Generated by Django 5.2.5 on 2025-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='quiz_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
