# Generated by Django 4.2.7 on 2025-10-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_academic_year_customuser_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='best_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
