# Generated by Django 5.2.5 on 2025-10-12 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='md_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='processing_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('pptx', 'PowerPoint'), ('png', 'PNG Image'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('txt', 'Text File'), ('md', 'Markdown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notes.note'),
        ),
    ]
