# Generated by Django 5.2.5 on 2025-10-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_checksum_file_language_file_md_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
